---
language: bash

os:
  - linux

services:
  - docker

# branches:
#   only:
#     - master

stages:
  - test
  - build_deploy

jobs:
  include:
    - stage: test
      name: "YamlLint"
      script: |
        docker run --rm -v $(pwd):/repo -it alpine:latest /bin/sh -c '
          cd /repo
          apk add --no-cache python3
          pip3 install yamllint
          yamllint .
        '
    - stage: test
      name: "ShellCheck"
      script: |
        docker run --rm -v $(pwd):/repo -it alpine:latest /bin/sh -c '
          cd /repo
          apk add --no-cache shellcheck bash
          shellcheck ./*.sh
        '
    - stage: build_deploy
      name: "Build Fedora"
      script: ./build_in_docker.sh
    - stage: build_deploy
      name: "Deploy to Github Releases"
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: "fedora-kickstarts/output_zip/*"
        skip_cleanup: true
        on:
          tags: true
