---
language: bash

os:
  - linux

services:
  - docker

# branches:
#   only:
#     - master

script:
  - docker pull fedora:31
  - |
    docker run \
      --privileged \
      -t \
      --rm \
      -v $(pwd):/repo \
      fedora:31 \
      /bin/bash -c 'cd /repo && ./build.sh'

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "fedora-kickstarts/output_zip/*"
  skip_cleanup: true
  on:
    tags: true
