---
language: bash

os:
  - linux

services:
  - docker

# branches:
#   only:
#     - master

script:
  - ./build_in_docker.sh

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "fedora-kickstarts/output_zip/*"
  skip_cleanup: true
  on:
    tags: true
