---
language: bash

os:
  - linux

services:
  - docker

# branches:
#   only:
#     - master

stages:
  - test
  - build
  - deploy

jobs:
  include:
    - stage: test
      name: "Lint"
      script: |
        docker run --rm -v $(pwd):/repo -it alpine:latest /bin/sh -c '
          cd /repo
          apk add --no-cache shellcheck python3 bash
          pip3 install yamllint
          yamllint .
          shellcheck ./*.sh
        '
    - stage: build
      name: "Build Fedora"
      script: ./build_in_docker.sh
    - stage: deploy
      name: Deploy to Github Releases
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: "fedora-kickstarts/output_zip/*"
        skip_cleanup: true
        on:
          tags: true
